### ISSUE TITLE
Set a GitHub Action to build predefined configurations.

### ISSUE THREAD

**Issue by C47D** [lvgl/lv_port_esp32#175]
We can use GitHub Actions to build predefined configurations, this builds can be triggered on Pull Requests, commits, manually, etc. This can help so build issues are discovered before the PRs are merged and without waiting for the manteiner to build locally.

I got a shell script that tries to set up a ubuntu machine be able to do this, it installs all the dependencies and sets up the ESP-IDF environment.

What do you think @kisvegabor, @embeddedt ?

**Comment by kisvegabor** [comment]
It's a good idea to use GitHub actions for testing. lvgl's [test file](https://github.com/lvgl/lvgl/blob/master/.github/workflows/ccpp.yml) might be a good starting point.

Maybe it might be worth separating the components first (i.e. make lvgl to ESP component). It seems we are not that far from that.
What do you think?

**Comment by C47D** [comment]
In case of the LVGL component I wanted to ask the Zephyr and Nuttx people what mean to them having a KConfig file on the LVGL main repo.

For the lvgl_esp32_drivers component we are taking a lot of time before making anything, I wanted to move the existing component code there and make improvements after that.

I checked the lvgl test file for the github actions, just wanted to ask you something, ESP-IDF have some requirements, one of them is CMake. If I want to install CMake on the test machine (ubuntu-latest), I can install it from the github actions repo. What about other requirements, like flex and bison, do you happen to know if I can do `sudo apt install flex bison` on the test machine?

**Comment by kisvegabor** [comment]
> For the lvgl_esp32_drivers component we are taking a lot of time before making anything, I wanted to move the existing component code there and make improvements after that.

Restructuring the drivers will really require some time, so I agree to use the current drivers first and improve them later. 

> What about other requirements, like flex and bison, do you happen to know if I can do sudo apt install flex bison on the test machine?

I don't know for sure, but if they can be installed this way, I see no problem with that. 
However, if they are really large (takes 10 minutes to install) we can consider using a docker file where the libs are preinstalled.

**Comment by C47D** [comment]
> However, if they are really large (takes 10 minutes to install) we can consider using a docker file where the libs are preinstalled.

You're right, there's quite a lot of requirements for ESP-IDF. I will take a look into Docker container and GitHub Actions, found this tutorial on a quick research: [Creating a Docker container action
](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)

**Comment by C47D** [comment]
> Restructuring the drivers will really require some time, so I agree to use the current drivers first and improve them later.

So you agree we move the current lvgl_esp32_drivers directory onto it's repo? Then @zladay can incorporate their improvements?

**Comment by kisvegabor** [comment]
Yes, I agree. But I assume that @zladay would rather rewrite than modify the driver. 
Anyway, we can decide it later.

**Comment by zladay** [comment]
@C47D 
>So you agree we move the current lvgl_esp32_drivers directory onto it's repo? Then @zladay can incorporate their improvements?

I can not incorporate anything, since I came up with a new structure. It has a completely different concept. The two are very far apart. They would mix a little less than oil and water.

@kisvegabor 
>But I assume that @zladay would rather rewrite than modify the driver.

There is not much to modify or rewrite. Comparing the hardware support capabilities of the two, mine is missing the monochrome stuff only (SSD1306, SH1107 and e-paper). The rest is supported now. Even 262k/16.7M color depth is supported with down converting from RGB8888.
As far as the TC is concerned, mine supports STMPE811/610 and XPT2046. No support for FT3236 and ESP based A/D conversion.
I am about to restructure the TC part, too. The hardware specific object will have minimal functionality: just reading the raw X, Y data. The rest (coordinate space conversion and orientation handling) will be in a different, hardware independent object. A specific TC "driver" in this framework will be really tiny. 

Whatever I am about to add to the existing hardware support will not be a modification or a rewrite of an existing one, but a new implementation from scratch. This is also what happened to what is already implemented.

I  report the progress [here](https://github.com/lvgl/lvgl_esp32_drivers/issues/1).

**Comment by C47D** [comment]
Not staled

**Comment by C47D** [comment]
on the backburner

**Comment by C47D** [comment]
Need more time to get this done.
