### ISSUE TITLE
FULL Duplex support on ILI9341 display driver.

### ISSUE THREAD

**Issue by C47D** [lvgl/lv_port_esp32#218]
Currently the only driver that supports (have code to do it) full duplex communication is the FT18x.

I need to read back some information from the ILI9341 driver, how can we add support for full duplex communication for it? driver-specific code, generic code?

**Comment by davidjade** [comment]
FULL Duplex literally means reading and writing at the same time - bits are transferring in both directions at the same time. Even thought the FT81x has code to do this, it doesn't really operate in full duplex mode. In full duplex mode, it sends some address bits and/or commands, ignores some dummy bits as required by the FT81x, and then receives some data. While it's sending data, it ignores any received data (treats them as dummy bits) and while it is reading data, the esp32 SPI driver just sends zeros. This is effectively half-duplex mode in reality and due to my misunderstanding, this is the way I first got things to work. Half duplex mode is the way I should have done things from the start and my recent changes enable it to work that way. I didn't fully disable full duplex mode though due to some quirks when reading large amounts of data (the FT81x one byte at a time hacks in half duplex config mode, which I am still not sure if it is an esp32 SPI driver bug or a quirk of the FT81x).

I don't know much about any other display controller but I would guess that they don't truly operate in full duplex mode either as what display needs to read & write at the same exact time. It probably requires some address and/or command bits to be sent and then responds with data. This is still technically half-duplex mode as it has a write (address & command) followed by a read (data returned). the esp32 SPI driver supports this in half duplex mode using the address and command bits (it just doesn't support writing arbitrary data in the same transaction). If it is not flexible enough, then you can fake it use full duplex by crafting the right bits to send (which is what the FT81x does in full duplex mode).

So I would check the data sheet to see if it really transfers and received simultaneously. If it does then it is truly full duplex. But if you send an address and/or command followed by reading data, then it is really half duplex. Either way the disp_spi.c supports both methods and since the FT81x can be configured to use either mode (even though it is not truly full duplex) it can serve as an example. Just note that dummy bits config is specific to the device used. Some may not need them at all. Also, I doubt I could have gotten this to work without a logic analyzer to see into the process to make sure it matches the datasheet but that was likely due to my lack of experience with esp32, SPI, etc...

Also, as for driver-specific or generic, it seems to me that reading data, dummy bits, timing, etc.. is going to be pretty specific to the device. In other words, it may be hard to make it generic enough to suit all the quirks of each devices.

I am in no way an expert on this - this is just what I figured out through trial and error for the FT81x.
